[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
acpi_tables = { path = "../acpi-tables" }
aes-gcm =  { version = "0.10.1", default-features = false, features = ["aes"] }
arrayvec = { version = "0.7.6", optional = true }
aws-lc-rs = { version = "1.12.4", features = ["bindgen"] }
base64 = "0.22.1"
bincode = "1.2.1"
bitflags = "2.8.0"
crc64 = "2.0.0"
derive_more = { version = "2.0.1", default-features = false, features = ["from", "display"] }
displaydoc = "0.2.5"
event-manager = "0.4.0"
gdbstub = { version = "0.7.3", optional = true }
gdbstub_arch = { version = "0.3.1", optional = true }
kvm-bindings = { version = "0.11.0", features = ["fam-wrappers", "serde"] }
kvm-ioctls = "0.20.0"
libc = "0.2.170"
linux-loader = "0.13.0"
log = { version = "0.4.26", features = ["std", "serde"] }
log-instrument = { path = "../log-instrument", optional = true }
memfd = "0.6.3"
micro_http = { git = "https://github.com/firecracker-microvm/micro-http" }

semver = { version = "1.0.25", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive", "rc"] }
serde_json = "1.0.139"
slab = "0.4.7"
thiserror = "2.0.11"
timerfd = "1.5.0"
userfaultfd = "0.8.1"
utils = { path = "../utils" }
vhost = { version = "0.13.0", features = ["vhost-user-frontend"] }
vm-allocator = "0.1.0"
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-bitmap"] }
vm-superio = "0.8.0"
vmm-sys-util = { version = "0.12.1", features = ["with-serde"] }
zerocopy = { version = "0.8.20" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
vm-fdt = "0.3.0"

[dev-dependencies]
criterion = { version = "0.5.0", default-features = false }
device_tree = "1.1.0"
itertools = "0.14.0"
proptest = { version = "1.6.0", default-features = false, features = ["std"] }

[features]
default = []
tracing = ["log-instrument"]
gdb = ["arrayvec", "gdbstub", "gdbstub_arch"]

[[bench]]
name = "cpu_templates"
harness = false

[[bench]]
name = "queue"
harness = false

[[bench]]
name = "block_request"
harness = false

[[bench]]
name = "memory_access"
harness = false

[lints]
workspace = true
